version: '3.0'

services:
  gateway:
    build:
      context: ./.docker/gateway
    depends_on:
      - server
    ports:
      - 30000:80
  server:
    image: node:12
    command: bash -c 'yarn install && npx lerna bootstrap && npx pm2 start --only=config && npx pm2 logs -f'
    working_dir: /app
    volumes:
      - ./:/app
