version: '3.0'

services:
  gateway:
    image: nginx
    volumes:
      - ./.docker/gateway:/etc/nginx/templates/
    depends_on:
      - server
    env_file: .env
    ports:
      - ${PUBLIC_PORT}:80
  server:
    build:
      context: ./.docker/server
    command: bash -c 'yarn install && npx lerna bootstrap && (yarn transpile:watch & (cd /app/packages/denim-platform/ && yarn server:dev) & (cd /app/packages/denim-platform-web/ && yarn start) & (cd /app/packages/denim-platform-admin/ && yarn start))'
    working_dir: /app
    env_file: .env
    volumes:
      - ./:/app
