version: '3.0'

services:
  gateway:
    build:
      context: ./.docker/gateway
    env_file: app.env
    depends_on:
      - server
    ports:
      - 30000:80
  server:
    build:
      context: ./.docker/server
    command: bash -c 'yarn install && npx lerna bootstrap && yarn transpile && ((cd /app/packages/denim-lemonade/ && yarn web) & (cd /app/packages/denim-server/ && yarn server:dev))'
    working_dir: /app
    env_file: app.env
    volumes:
      - ./:/app
