version: '3.0'

services:
  gateway:
    build:
      context: ./.docker/gateway
    env_file: app.env
    depends_on:
      - server
    ports:
      - 80:80
  server:
    image: node:12
    command: bash -c 'yarn install && npx lerna bootstrap && yarn transpile && cd /app/packages/denim-lemonade/ && ((cd /app/packages/denim-lemonade/ && PORT=3000 npx serve) & (cd /app/packages/denim-lemonade-server/ && yarn server))'
    working_dir: /app
    env_file: app.env
    restart: always
    volumes:
      - ./:/app
