version: '3.0'

services:
  gateway:
    build:
      context: ./.docker/gateway
    env_file: app.env
    depends_on:
      - server
      - frontend
    ports:
      - 30000:80
  server:
    build:
      context: ./.docker/server
    command: bash -c 'yarn install && npx lerna bootstrap && cd /app/packages/denim-lemonade/ && yarn server:dev'
    working_dir: /app
    env_file: app.env
    volumes:
      - ./:/app
  frontend:
    image: node:12
    command: bash -c 'cd /app/packages/denim-lemonade/ && yarn web'
    working_dir: /app
    env_file: app.env
    depends_on:
      - server
    restart: always
    volumes:
      - ./:/app
