version: '3.0'

services:
  gateway:
    build:
      context: ./.docker/gateway
    env_file: app.env
    ports:
      - 80:80
  server:
    image: node:12
    command: bash -c 'yarn install && yarn build && (yarn serve & yarn server:dev)'
    working_dir: /app
    env_file: app.env
    volumes:
      - ./:/app
